# Pandas

In [4]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv('elections.csv')

In [6]:
df

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789
...,...,...,...,...,...,...
177,2016,Jill Stein,Green,1457226,loss,1.073699
178,2020,Joseph Biden,Democratic,81268924,win,51.311515
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [5]:
df.shape

(182, 6)

In [6]:
print(df.columns)

Index(['Year', 'Candidate', 'Party', 'Popular vote', 'Result', '%'], dtype='object')

In [7]:
print(df['Candidate'])

0         Andrew Jackson
1      John Quincy Adams
2         Andrew Jackson
3      John Quincy Adams
4         Andrew Jackson
             ...
177           Jill Stein
178         Joseph Biden
179         Donald Trump
180         Jo Jorgensen
181       Howard Hawkins
Name: Candidate, Length: 182, dtype: object

In [8]:
df[df['Year'] == 1828]

,Year,Candidate,Party,Popular vote,Result,%
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073

In [9]:
df.loc[df['Party'] == 'Democratic']

     Year               Candidate       Party  Popular vote Result          %
2    1828          Andrew Jackson  Democratic        642806    win  56.203927
4    1832          Andrew Jackson  Democratic        702735    win  54.574789
8    1836        Martin Van Buren  Democratic        763291    win  52.272472
10   1840        Martin Van Buren  Democratic       1128854   loss  46.948787
13   1844              James Polk  Democratic       1339570    win  50.749477
14   1848              Lewis Cass  Democratic       1223460   loss  42.552229
17   1852         Franklin Pierce  Democratic       1605943    win  51.013168
20   1856          James Buchanan  Democratic       1835140    win  45.306080
28   1864     George B. McClellan  Democratic       1812807   loss  45.048488
29   1868         Horatio Seymour  Democratic       2708744   loss  47.334695
34   1876        Samuel J. Tilden  Democratic       4288546   loss  51.528376
37   1880  Winfield Scott Hancock  Democratic       4444976   loss  48.278422
39   1884        Grover Cleveland  Democratic       4914482    win  48.884933
45   1888        Grover Cleveland  Democratic       5534488   loss  48.656799
47   1892        Grover Cleveland  Democratic       5553898    win  46.121393
52   1896  William Jennings Bryan  Democratic       6509052   loss  46.871053
55   1900  William Jennings Bryan  Democratic       6370932   loss  46.130540
57   1904         Alton B. Parker  Democratic       5083880   loss  37.685116
64   1908  William Jennings Bryan  Democratic       6408979   loss  43.414640
70   1912          Woodrow Wilson  Democratic       6296284    win  41.933422
74   1916          Woodrow Wilson  Democratic       9126868    win  49.367987
77   1920            James M. Cox  Democratic       9139661   loss  34.293063
81   1924           John W. Davis  Democratic       8386242   loss  28.976291
83   1928                Al Smith  Democratic      15015464   loss  40.902853
86   1932      Franklin Roosevelt  Democratic      22821277    win  57.672125
91   1936      Franklin Roosevelt  Democratic      27752648    win  60.978107
94   1940      Franklin Roosevelt  Democratic      27313945    win  54.871202
97   1944      Franklin Roosevelt  Democratic      25612916    win  53.773801
100  1948            Harry Truman  Democratic      24179347    win  49.601536
105  1952         Adlai Stevenson  Democratic      27375090   loss  44.446312
108  1956         Adlai Stevenson  Democratic      26028028   loss  42.174464
111  1960            John Kennedy  Democratic      34220984    win  50.082561
114  1964          Lyndon Johnson  Democratic      43127041    win  61.344703
116  1968         Hubert Humphrey  Democratic      31271839   loss  42.863537
118  1972         George McGovern  Democratic      29173222   loss  37.670670
123  1976            Jimmy Carter  Democratic      40831881    win  50.271900
129  1980            Jimmy Carter  Democratic      35480115   loss  41.132848
134  1984          Walter Mondale  Democratic      37577352   loss  40.729429
137  1988         Michael Dukakis  Democratic      41809074   loss  45.770691
140  1992            Bill Clinton  Democratic      44909806    win  43.118485
144  1996            Bill Clinton  Democratic      47400125    win  49.296938
151  2000                 Al Gore  Democratic      50999897   loss  48.491813
158  2004              John Kerry  Democratic      59028444   loss  48.306775
162  2008            Barack Obama  Democratic      69498516    win  53.023510
168  2012            Barack Obama  Democratic      65915795    win  51.258484
176  2016         Hillary Clinton  Democratic      65853514   loss  48.521539
178  2020            Joseph Biden  Democratic      81268924    win  51.311515

In [17]:
df.loc[df['Result']=='win',['Year','Popular vote']]

     Year  Popular vote
1    1824        113142
2    1828        642806
4    1832        702735
8    1836        763291
11   1840       1275583
13   1844       1339570
16   1848       1360235
17   1852       1605943
20   1856       1835140
23   1860       1855993
27   1864       2211317
30   1868       3013790
32   1872       3597439
33   1876       4034142
36   1880       4453337
39   1884       4914482
43   1888       5443633
47   1892       5553898
53   1896       7112138
56   1900       7228864
60   1904       7630557
65   1908       7678335
70   1912       6296284
74   1916       9126868
79   1920      16144093
80   1924      15723789
84   1928      21427123
86   1932      22821277
91   1936      27752648
94   1940      27313945
97   1944      25612916
100  1948      24179347
106  1952      34075529
109  1956      35579180
111  1960      34220984
114  1964      43127041
117  1968      31783783
120  1972      47168710
123  1976      40831881
131  1980      43903230
133  1984      54455472
135  1988      48886597
140  1992      44909806
144  1996      47400125
152  2000      50456002
157  2004      62040610
162  2008      69498516
168  2012      65915795
173  2016      62984828
178  2020      81268924

In [16]:
df.loc[df['Year']==1828]

,Year,Candidate,Party,Popular vote,Result,%
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073

In [19]:
df.loc[df['%'] > 55]

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
32,1872,Ulysses Grant,Republican,3597439,win,55.928594
60,1904,Theodore Roosevelt,Republican,7630557,win,56.562787
79,1920,Warren Harding,Republican,16144093,win,60.574501
84,1928,Herbert Hoover,Republican,21427123,win,58.368524
86,1932,Franklin Roosevelt,Democratic,22821277,win,57.672125
91,1936,Franklin Roosevelt,Democratic,27752648,win,60.978107
106,1952,Dwight Eisenhower,Republican,34075529,win,55.325173
109,1956,Dwight Eisenhower,Republican,35579180,win,57.650654
114,1964,Lyndon Johnson,Democratic,43127041,win,61.344703
120,1972,Richard Nixon,Republican,47168710,win,60.907806
133,1984,Ronald Reagan,Republican,54455472,win,59.023326

In [22]:
df.iloc[:5,:]

,Year,Candidate,Party,Popular vote,Result,%
0,1824,Andrew Jackson,Democratic-Republican,151271,loss,57.210122
1,1824,John Quincy Adams,Democratic-Republican,113142,win,42.789878
2,1828,Andrew Jackson,Democratic,642806,win,56.203927
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
4,1832,Andrew Jackson,Democratic,702735,win,54.574789

In [25]:
df.iloc[1:5,:3]

   Year          Candidate                  Party
1  1824  John Quincy Adams  Democratic-Republican
2  1828     Andrew Jackson             Democratic
3  1828  John Quincy Adams    National Republican
4  1832     Andrew Jackson             Democratic

In [30]:
df.iloc[:10,[3,4]]

   Popular vote Result
0        151271   loss
1        113142    win
2        642806    win
3        500897   loss
4        702735    win
5        484205   loss
6        100715   loss
7        146109   loss
8        763291    win
9        550816   loss

In [32]:
df.loc[(df['Result'] == 'loss') & (df['%']<50)]

,Year,Candidate,Party,Popular vote,Result,%
3,1828,John Quincy Adams,National Republican,500897,loss,43.796073
5,1832,Henry Clay,National Republican,484205,loss,37.603628
6,1832,William Wirt,Anti-Masonic,100715,loss,7.821583
7,1836,Hugh Lawson White,Whig,146109,loss,10.005985
9,1836,William Henry Harrison,Whig,550816,loss,37.721543
...,...,...,...,...,...,...
176,2016,Hillary Clinton,Democratic,65853514,loss,48.521539
177,2016,Jill Stein,Green,1457226,loss,1.073699
179,2020,Donald Trump,Republican,74216154,loss,46.858542
180,2020,Jo Jorgensen,Libertarian,1865724,loss,1.177979
181,2020,Howard Hawkins,Green,405035,loss,0.255731

In [38]:
df.loc[df['Candidate'].isin(['Democratic','Republican']) & df['Result']=='won']

Empty DataFrame
Columns: [Year, Candidate, Party, Popular vote, Result, %]
Index: []

# QUIZ

### Using loc

1.  Extract all rows for the candidate 'Andrew Jackson' and display the columns 'Year',
'Popular vote', and 'Result'

In [10]:
df.loc[df['Candidate']=='Andrew Jackson',['Year','Popular vote','Result']]

   Year  Popular vote Result
0  1824        151271   loss
2  1828        642806    win
4  1832        702735    win

2. Use `loc` to extract all rows where the candidate's `Party` is 'Democratic' and display
the 'Year', 'Candidate', and 'Result'.

In [11]:
df.loc[df['Party'] == 'Democratic',['Year','Candidate','Result']]

     Year               Candidate Result
2    1828          Andrew Jackson    win
4    1832          Andrew Jackson    win
8    1836        Martin Van Buren    win
10   1840        Martin Van Buren   loss
13   1844              James Polk    win
14   1848              Lewis Cass   loss
17   1852         Franklin Pierce    win
20   1856          James Buchanan    win
28   1864     George B. McClellan   loss
29   1868         Horatio Seymour   loss
34   1876        Samuel J. Tilden   loss
37   1880  Winfield Scott Hancock   loss
39   1884        Grover Cleveland    win
45   1888        Grover Cleveland   loss
47   1892        Grover Cleveland    win
52   1896  William Jennings Bryan   loss
55   1900  William Jennings Bryan   loss
57   1904         Alton B. Parker   loss
64   1908  William Jennings Bryan   loss
70   1912          Woodrow Wilson    win
74   1916          Woodrow Wilson    win
77   1920            James M. Cox   loss
81   1924           John W. Davis   loss
83   1928                Al Smith   loss
86   1932      Franklin Roosevelt    win
91   1936      Franklin Roosevelt    win
94   1940      Franklin Roosevelt    win
97   1944      Franklin Roosevelt    win
100  1948            Harry Truman    win
105  1952         Adlai Stevenson   loss
108  1956         Adlai Stevenson   loss
111  1960            John Kennedy    win
114  1964          Lyndon Johnson    win
116  1968         Hubert Humphrey   loss
118  1972         George McGovern   loss
123  1976            Jimmy Carter    win
129  1980            Jimmy Carter   loss
134  1984          Walter Mondale   loss
137  1988         Michael Dukakis   loss
140  1992            Bill Clinton    win
144  1996            Bill Clinton    win
151  2000                 Al Gore   loss
158  2004              John Kerry   loss
162  2008            Barack Obama    win
168  2012            Barack Obama    win
176  2016         Hillary Clinton   loss
178  2020            Joseph Biden    win

3. Extract rows where the `Popular vote` is greater than 600000 and display the
'Candidate' and 'Party' columns.